[default]
DEBUG = false
EXTENSIONS = [
    "api.extensions.restful:init_app",
]


[development]
LOCAL_CONNCTION = "localhost:27017"
DB_NAME = "imoveis_natal"
EXTENSIONS = [
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
DEBUG = true


[production]
DEBUG = false